// contests.njmonthly.com/src/components/super/SuperContestsContestUpdate.vue
<template>
  <div>
    <super-header></super-header>

    <div v-if="entryForm && entry">

      <entry-form @submitted="formSubmitted"></entry-form>

    </div>
  </div>
</template>
<script>
import EntryForm from 'components/contests/EntryForm.vue';
import {ENV_URL, MAIN_URL, STRIPE_PUBLISHABLE} from '../../environment.js';
import axios from 'axios';
import SuperHeader from 'components/super/SuperHeader.vue';

export default {
  name: 'directory-view',

  components: {
    EntryForm,
    SuperHeader,
  },
  data () {
    console.log('current page', this.$route)
    return {
    }

  },
  created() {

    this.$store.dispatch('LOADING', true);

    const uri = ENV_URL + this.$route.path;

    this.$store.dispatch('SUPER_ENTRIES_ENTRY_UPDATE', {uri: uri}).then(() => {

      this.$store.dispatch('LOADING', false);

    })

  },

  computed: {
    user() {
      return this.$store.state.user;
    },
    entryForm() {
      return this.$store.state.entryForm;
    },
    entry() {
      return this.$store.state.entry;
    },
  },

  mounted() {

  },

  methods: {
    formSubmitted(e) {

      this.$store.dispatch('LOADING', true);

      var laravelAuthToken = localStorage.getItem('laravelAuthToken');

      let authHeaders = {
        headers: {"Authorization" : `Bearer ${laravelAuthToken}`}
      };

      const item_data = {
        form_data: this.entryForm.fields,
      }

      // /super/contests/{contest}/entries/{id}/update
      let uri = ENV_URL + this.$route.path;
      axios.patch(uri, item_data, authHeaders).then((response) => {
        this.$store.dispatch('LOADING', false);
        alert('Your item was updated!');
      });
    },

  },

}
</script>

<style lang="scss">

</style>

// contests.njmonthly.com/src/components/super-react/SuperContestsContestUpdate.js
import React, {Component} from 'react';
import axios from 'axios';
import {ENV_URL} from '../../environment';
import SuperHeader from './SuperHeader';
import ContestForm from './ContestForm';

export default class SuperContestsContestUpdate extends Component {
  constructor(props) {
    super(props);
    this.state = {
      page: {}
    }

    this.formSubmitted = this.formSubmitted.bind(this);
    this.setContestFormData = this.setContestFormData.bind(this);
  }

  componentDidMount() {
    // super/contests/{contest}/update
    axios.get(ENV_URL + window.location.pathname)
    .then(response => {

      console.log('res', response);

      let contestForm = response.data.contestForm;
      let contest = response.data.contest;

      this.setState({ 
        contestForm: contestForm,
        contest: contest
      });

    })
    .catch(function (error) {
      console.log(error);
    })

  }

  formSubmitted(e) {
    e.preventDefault();
    var laravelAuthToken = localStorage.getItem('laravelAuthToken');

    let authHeaders = {
      headers: {"Authorization" : `Bearer ${laravelAuthToken}`}
    };

    // /super/contests/{contest}/contests/{id}/update
    let uri = ENV_URL + this.props.location.pathname;

    let data = {
      form_data: this.state.contestForm.fields,
    }

    axios.patch(uri, data, authHeaders).then((response) => {

      console.log('update res', response);

      if (response.data.error === false) {
        alert('Page updated.');
      }
      
    });
  }

  setContestFormData(contestFormData) {
    this.setState({
      contestFormData: contestFormData
    })
  }

  render() {
    return (
      <div>

        {/* <SuperHeader /> */}
        
        {this.state.contestForm ? <ContestForm
          formSubmitted={this.formSubmitted}
          contestForm={this.state.contestForm}
          contest={this.state.contest}
          setContestFormData={this.setContestFormData}
        /> : '' }
      </div>
    )
  }
}
